// Copyright 2024 Nokia
// Licensed under the BSD 3-Clause Clear License.
// SPDX-License-Identifier: BSD-3-Clause-Clear

//! This module contains the ABIs of the ZoKrates programs.
//! They were derived from the *.abi.json files generated by ZoKrates.

#![allow(non_snake_case)]

use serde::{Deserialize, Serialize};
use serde_tuple::{Deserialize_tuple, Serialize_tuple};

/// Field is encoded as a string containing the number, e.g. "123".
pub type Field = String;

/// Other number (u32, u64, etc.) are encoded as a hexadecimal number in a
/// string, e.g. "0x123".
pub type Number = String;

pub type HashPoseidon = Field;

pub type SaltPoseidon = [Field; 4];

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct PublicKey {
    pub x: Field,
    pub y: Field,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Signature {
    pub Rx: Field,
    pub Ry: Field,
    pub S: Field,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct MessageMetadata {
    pub deviceId: Number,
    pub messageId: Number,
    pub timestamp: Number,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Bid {
    pub auction: Number,
    pub price: Number,
}

/// Generic in N
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Bids {
    pub values: Vec<Bid>, // Size N
    pub n: Number,
}

/// Generic in N
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct U64s {
    pub values: Vec<Number>, // Size N
    pub n: Number,
}

/// Based on q1.poseidon.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q1PoseidonAbi {
    pub publicKey: PublicKey,
    pub msgs: Vec<MessageMetadata>, // size N_MESSAGES
    pub bids: Bids,                 // size N_MESSAGES
    pub signatures: Vec<Signature>, // size N_MESSAGES
}

/// Based on q1.poseidon.nosig.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q1PoseidonNoSigAbi {
    pub msgs: Vec<MessageMetadata>, // size N_MESSAGES
    pub bids: Bids,                 // size N_MESSAGES
    pub salts: Vec<SaltPoseidon>,   // size N_MESSAGES
}

/// Based on q4a.poseidon.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q4aPoseidonAbi {
    pub publicKey: PublicKey,
    pub msgs: Vec<MessageMetadata>, // size N_MESSAGES
    pub bids: Bids,                 // size N_MESSAGES
    pub signatures: Vec<Signature>, // size N_MESSAGES
    pub outputSalt: SaltPoseidon,
}

/// Based on q4a.poseidon.nosig.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q4aPoseidonNoSigAbi {
    pub msgs: Vec<MessageMetadata>, // size N_MESSAGES
    pub bids: Bids,                 // size N_MESSAGES
    pub salts: Vec<SaltPoseidon>,   // size N_MESSAGES
    pub outputSalt: SaltPoseidon,
}

/// Based on q4b.poseidon.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q4bPoseidonAbi {
    pub valsHashes: Vec<HashPoseidon>, // size N_MESSAGES
    pub vals: U64s,                    // size N_MESSAGES
    pub salts: Vec<SaltPoseidon>,      // size N_MESSAGES
}

/// Based on q4b.poseidon.nosig.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q4bPoseidonNoSigAbi {
    pub valsHashes: Vec<HashPoseidon>, // size N_MESSAGES
    pub vals: U64s,                    // size N_MESSAGES
    pub salts: Vec<SaltPoseidon>,      // size N_MESSAGES
}

/// Based on q5a.poseidon.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q5aPoseidonAbi {
    pub publicKey: PublicKey,
    pub msgs: Vec<MessageMetadata>, // size N_MESSAGES
    pub bids: Bids,                 // size N_MESSAGES
    pub signatures: Vec<Signature>, // size N_MESSAGES
    pub outputSalt: SaltPoseidon,
}

/// Based on q5a.poseidon.nosig.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q5aPoseidonNoSigAbi {
    pub msgs: Vec<MessageMetadata>, // size N_MESSAGES
    pub bids: Bids,                 // size N_MESSAGES
    pub salts: Vec<SaltPoseidon>,   // size N_MESSAGES
    pub outputSalt: SaltPoseidon,
}

/// Based on q5b.poseidon.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q5bPoseidonAbi {
    pub valsHashes: Vec<HashPoseidon>, // size N_MESSAGES
    pub vals: U64s,                    // size N_MESSAGES
    pub salts: Vec<SaltPoseidon>,      // size N_MESSAGES
}

/// Based on q5b.poseidon.nosig.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q5bPoseidonNoSigAbi {
    pub valsHashes: Vec<HashPoseidon>, // size N_MESSAGES
    pub vals: U64s,                    // size N_MESSAGES
    pub salts: Vec<SaltPoseidon>,      // size N_MESSAGES
}

/// Based on q6a.poseidon.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q6aPoseidonAbi {
    pub publicKey: PublicKey,
    pub msgs: Vec<MessageMetadata>, // size N_MESSAGES
    pub bids: Bids,                 // size N_MESSAGES
    pub signatures: Vec<Signature>, // size N_MESSAGES
    pub outputSalt: SaltPoseidon,
}

/// Based on q6a.poseidon.nosig.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q6aPoseidonNoSigAbi {
    pub msgs: Vec<MessageMetadata>, // size N_MESSAGES
    pub bids: Bids,                 // size N_MESSAGES
    pub salts: Vec<SaltPoseidon>,   // size N_MESSAGES
    pub outputSalt: SaltPoseidon,
}

/// Based on q6b.poseidon.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q6bPoseidonAbi {
    pub valsHashes: Vec<HashPoseidon>, // size N_MESSAGES
    pub vals: U64s,                    // size N_MESSAGES
    pub salts: Vec<SaltPoseidon>,      // size N_MESSAGES
}

/// Based on q6b.poseidon.nosig.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q6bPoseidonNoSigAbi {
    pub valsHashes: Vec<HashPoseidon>, // size N_MESSAGES
    pub vals: U64s,                    // size N_MESSAGES
    pub salts: Vec<SaltPoseidon>,      // size N_MESSAGES
}

/// Based on q7.poseidon.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q7PoseidonAbi {
    pub publicKey: PublicKey,
    pub msgs: Vec<MessageMetadata>, // size N_MESSAGES
    pub bids: Bids,                 // size N_MESSAGES
    pub signatures: Vec<Signature>, // size N_MESSAGES
}

/// Based on q7.poseidon.nosig.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct Q7PoseidonNoSigAbi {
    pub msgs: Vec<MessageMetadata>, // size N_MESSAGES
    pub bids: Bids,                 // size N_MESSAGES
    pub salts: Vec<SaltPoseidon>,   // size N_MESSAGES
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Abi {
    Q1Poseidon(Q1PoseidonAbi),
    Q1PoseidonNoSig(Q1PoseidonNoSigAbi),
    Q4aPoseidon(Q4aPoseidonAbi),
    Q4aPoseidonNoSig(Q4aPoseidonNoSigAbi),
    Q4bPoseidon(Q4bPoseidonAbi),
    Q4bPoseidonNoSig(Q4bPoseidonNoSigAbi),
    Q5aPoseidon(Q5aPoseidonAbi),
    Q5aPoseidonNoSig(Q5aPoseidonNoSigAbi),
    Q5bPoseidon(Q5bPoseidonAbi),
    Q5bPoseidonNoSig(Q5bPoseidonNoSigAbi),
    Q6aPoseidon(Q6aPoseidonAbi),
    Q6aPoseidonNoSig(Q6aPoseidonNoSigAbi),
    Q6bPoseidon(Q6bPoseidonAbi),
    Q6bPoseidonNoSig(Q6bPoseidonNoSigAbi),
    Q7Poseidon(Q7PoseidonAbi),
    Q7PoseidonNoSig(Q7PoseidonNoSigAbi),
}
