//! This module contains the ABIs of the ZoKrates programs.
//! They were derived from the *.abi.json files generated by ZoKrates.

#![allow(non_snake_case)]

use serde::{Deserialize, Serialize};
use serde_tuple::{Deserialize_tuple, Serialize_tuple};

/// Field is encoded as a string containing the number, e.g. "123".
pub type Field = String;

/// Other numbers are encoded as a hexadecimal number in a string, e.g. "0x123".
pub type Number = String;

pub type HashPoseidon = Field;

pub type SaltPoseidon = [Field; 4];

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct PublicKey {
    pub x: Field,
    pub y: Field,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct MessageMetadata {
    pub deviceId: Number,
    pub messageId: Number,
    pub timestamp: Number,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Signature {
    pub Rx: Field,
    pub Ry: Field,
    pub S: Field,
}

/// Based on flexibility.poseidon.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct FlexibilityPoseidonAbi {
    pub publicKey: PublicKey,
    pub msgsBefore: Vec<MessageMetadata>, // size N_BEFORE
    pub msgsAfter: Vec<MessageMetadata>,  // size N_AFTER
    pub valsBefore: Vec<Number>,          // size N_BEFORE
    pub valsAfter: Vec<Number>,           // size N_AFTER
    pub signaturesBefore: Vec<Signature>, // size N_BEFORE
    pub signaturesAfter: Vec<Signature>,  // size N_AFTER
}

/// Based on flexibility.poseidon.nosig.abi.json.
#[derive(Clone, Debug, PartialEq, Eq, Serialize_tuple, Deserialize_tuple)]
pub struct FlexibilityPoseidonNoSigAbi {
    pub msgsBefore: Vec<MessageMetadata>, // size N_BEFORE
    pub msgsAfter: Vec<MessageMetadata>,  // size N_AFTER
    pub valsBefore: Vec<Number>,          // size N_BEFORE
    pub valsAfter: Vec<Number>,           // size N_AFTER
    pub saltsBefore: Vec<SaltPoseidon>,   // size N_BEFORE
    pub saltsAfter: Vec<SaltPoseidon>,    // size N_AFTER
}
