[package]
name = "aggsigs"
version = "1.0.0"
edition = "2021"
license = "BSD-3-Clause-Clear"

[lib]
name = "aggsigs" # the same as py module in BLS (main)

[dependencies]
blst = "0.3.10"
rand_chacha = "0.3.1"
rand_core = {version="0.6.4", features=["getrandom"]}
hex = "0.4.3"
blake3 = "1.3.3"
